import Head from "next/head";
import { useEffect, useState } from "react";
import { CurrentWeather } from "../components/CurrentWeather";
import { Favourites } from "../components/Favourites";
import { MapBoxSearch } from "../components/MapBoxSearch";
import { ModalContainer } from "../components/ModalContainer";

export default function Home() {
  const [center, setCenter] = useState([-73.9866, 40.7306]);
  const [placeName, setPlaceName] = useState("New York, USA");
  const [showFavourites, setShowFavourites] = useState(false);
  const [favouritesList, setFavouritesList] = useState([]);

  const onSetPlace = (center, name) => {
    console.log(center, name);
    setCenter(center);
    setPlaceName(name);
  };

  useEffect(() => {
    const savedFavourites = window.localStorage.getItem("favourites");
    if (savedFavourites) {
      setFavouritesList(JSON.parse(savedFavourites));
    }
  }, []);

  const handleFavouriteClick = (isFavourite) => {
    if (isFavourite) {
      removeFromFavourites();
    } else {
      addToFavourites();
    }
    const savedFavourites = window.localStorage.getItem("favourites");
    if (savedFavourites) {
      setFavouritesList(JSON.parse(savedFavourites));
    }
  };

  const removeFromFavourites = () => {
    const savedFavourites = window.localStorage.getItem("favourites");
    const parsedFavourites = JSON.parse(savedFavourites);

    const filteredFavourites = parsedFavourites.filter(
      (place) => place.place_name !== placeName
    );

    window.localStorage.setItem(
      "favourites",
      JSON.stringify(filteredFavourites)
    );
  };

  const addToFavourites = () => {
    const savedFavourites = window.localStorage.getItem("favourites");

    if (!savedFavourites) {
      console.log("no favs");
      window.localStorage.setItem(
        "favourites",
        JSON.stringify([{ center, place_name: placeName }])
      );
    } else {
      const parsedFavourites = JSON.parse(savedFavourites);
      console.log("have favs: ", parsedFavourites);
      parsedFavourites.push({ center, place_name: placeName });
      window.localStorage.setItem(
        "favourites",
        JSON.stringify(parsedFavourites)
      );
    }
  };

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="p-4 max-w-3xl mx-auto">
        <div className="flex flex-col gap-y-2">
          <div className="text-2xl text-center font-black">
            Just Another Weather App
          </div>
          <MapBoxSearch onSetPlace={onSetPlace} />
          <button
            onClick={() => setShowFavourites(true)}
            className="md:hidden rounded border p-1 text-sky-500"
          >
            Favourites
          </button>
          <div className="md:flex md:flex-row">
            <div className="hidden md:block md:w-4/12">
              <Favourites
                onSetPlace={onSetPlace}
                setShowFavourites={setShowFavourites}
                favouritesList={favouritesList}
              />
            </div>
            <div className="w-full md:w-8/12">
              <CurrentWeather
                handleFavouriteClick={handleFavouriteClick}
                center={center}
                placeName={placeName}
                favouritesList={favouritesList}
              />
            </div>
          </div>
        </div>
      </div>
      {showFavourites && (
        <ModalContainer setShowModal={setShowFavourites}>
          <Favourites
            onSetPlace={onSetPlace}
            setShowFavourites={setShowFavourites}
            favouritesList={favouritesList}
          />
        </ModalContainer>
      )}
    </div>
  );
}
